import { withTransaction } from '../postgres.js';
import { markWutCaptainPatchRole, WUT_CAPTAIN_PATCH_LIMIT, wutCaptainPatchCount } from '../../services/arenaRuntime.js';
import { lockWardingChoices, trinketFitsWutPosition } from '../../services/wutBalanceRules.js';

const clone = value => structuredClone(value || {}); const slots=['F1','F2','D1','D2','G'];
const keyFor = userId => `admin:${Number(userId)}`;
export async function getWutDebugMatchPostgres(pool, adminUserId) {
  const row=(await pool.query("SELECT data FROM card_records WHERE collection='debug_matches' AND record_key=$1",[keyFor(adminUserId)])).rows[0]; return row?clone(row.data):null;
}
export async function resetWutDebugMatchWithClient(client, adminUserId, now=new Date()) {
  await client.query('SELECT pg_advisory_xact_lock($1)',[8242044]); const id=Number((await client.query("SELECT COALESCE(max(source_order),0)+1 AS id FROM card_records WHERE collection='debug_matches'")).rows[0].id); const match={id:`debug-${id}`,admin_user_id:Number(adminUserId),player_ids:[-1,-2],rules_version:2,debug:true,placements:[],status:'setup',scores:null,winner_side:null,created_at:now.toISOString(),completed_at:null};
  await client.query(`INSERT INTO card_records(collection,record_key,user_id,record_id,source_order,data) VALUES('debug_matches',$1,$2,$3,$4,$5::jsonb) ON CONFLICT(collection,record_key) DO UPDATE SET record_id=EXCLUDED.record_id,source_order=EXCLUDED.source_order,data=EXCLUDED.data`,[keyFor(adminUserId),Number(adminUserId),id,id,JSON.stringify(match)]); return match;
}
export async function commitWutDebugPlacementWithClient(client,{adminUserId,side,slot,cardSnapshot,boost=null,journeymanKey='',wardTargetSlot='',config,now=new Date()}) {
  const key=keyFor(adminUserId); const row=(await client.query("SELECT data FROM card_records WHERE collection='debug_matches' AND record_key=$1 FOR UPDATE",[key])).rows[0]; const match=row?.data;
  if(!match||match.status!=='setup') throw new Error('Reset the admin debug game before adding cards.'); const cleanSide=String(side||'').toUpperCase(); const sideId=cleanSide==='A'?-1:cleanSide==='B'?-2:null; const cleanSlot=String(slot||'').toUpperCase();
  if(!sideId||!slots.includes(cleanSlot)) throw new Error('Invalid debug side or slot.'); if(match.placements.some(item=>Number(item.user_id)===sideId&&item.slot===cleanSlot)) throw new Error('That debug slot is already filled.');
  if(!cardSnapshot||cardSnapshot.position!==(cleanSlot==='G'?'G':cleanSlot[0])) throw new Error(`That card is not eligible for ${cleanSlot}.`); if(!trinketFitsWutPosition(cardSnapshot.trinket?.family,cardSnapshot.position)) throw new Error('That trinket is not legal for this card position.');
  const own=match.placements.filter(item=>Number(item.user_id)===sideId); if(own.some(item=>Number(item.card_id)===Number(cardSnapshot.card_id)||item.card_snapshot?.card_identity===cardSnapshot.card_identity)) throw new Error('That player card is already in this debug lineup.');
  let placedSnapshot=cardSnapshot;
  if(cardSnapshot.trinket?.family==='team_crest'){const captainCount=wutCaptainPatchCount(match.placements,sideId);if(captainCount>=WUT_CAPTAIN_PATCH_LIMIT) throw new Error(`Only ${WUT_CAPTAIN_PATCH_LIMIT} Captain's Patches can be active on each debug side.`);placedSnapshot=markWutCaptainPatchRole(cardSnapshot,captainCount);}
  const opposite=match.placements.find(item=>Number(item.user_id)!==sideId&&item.slot===cleanSlot); if(opposite&&Number(cardSnapshot.power)>Number(opposite.power)+Number(config.wut.slotPowerAllowance||1)) throw new Error(`${cleanSlot} exceeds the opposing card's Power +${config.wut.slotPowerAllowance}.`);
  if(boost&&own.some(item=>Number(item.boost_id)===Number(boost.id))) throw new Error('That debug boost is unavailable on this side.'); const goalieBoost=boost&&['save','shutout'].includes(boost.boost_type); if(boost&&(cardSnapshot.position==='G')!==goalieBoost) throw new Error('That boost does not fit this position.');
  const load=boost?Number(config.wut.rarityCosts?.[boost.rarity]||1):0; const used=own.reduce((sum,item)=>sum+Number(item.boost_load||0),0); const cable=Math.max(0,...[...own.map(item=>item.card_snapshot),placedSnapshot].filter(item=>item?.trinket?.family==='booster_cable').map(item=>Number(item.trinket.effect?.loadBonus||0))); const cap=Number(config.wut.boostLoadCap||5)+cable; if(used+load>cap) throw new Error(`That boost exceeds this side's ${cap} Boost Load.`);
  const placement={user_id:sideId,owner_user_id:Number(adminUserId),debug_side:cleanSide,slot:cleanSlot,card_id:Number(placedSnapshot.card_id),card_snapshot:clone(placedSnapshot),power:Number(placedSnapshot.power),boost_id:boost?.id||null,boost_load:load,journeyman_key:String(journeymanKey||''),ward_target_slot:String(wardTargetSlot||'').toUpperCase(),committed_at:now.toISOString()};
  lockWardingChoices(match.placements,[placement]); match.placements.push(placement); if(match.placements.length===10) match.status='scoring';
  await client.query("UPDATE card_records SET data=$2::jsonb WHERE collection='debug_matches' AND record_key=$1",[key,JSON.stringify(match)]); return match;
}
export async function getWutDebugMatchesNeedingScoringPostgres(pool){const rows=await pool.query("SELECT data FROM card_records WHERE collection='debug_matches' AND data->>'status'='scoring'");return rows.rows.map(row=>clone(row.data));}
export async function completeWutDebugMatchWithClient(client,{adminUserId,scoredPlacements,now=new Date()}){const key=keyFor(adminUserId);const row=(await client.query("SELECT data FROM card_records WHERE collection='debug_matches' AND record_key=$1 FOR UPDATE",[key])).rows[0];const match=row?.data;if(!match||match.status!=='scoring')throw new Error('Debug match is not awaiting scoring.');match.placements=clone(scoredPlacements);match.scores=Object.fromEntries([-1,-2].map(id=>[String(id),match.placements.filter(item=>Number(item.user_id)===id).reduce((sum,item)=>sum+Number(item.fp||0),0)]));match.winner_side=match.scores['-1']===match.scores['-2']?null:match.scores['-1']>match.scores['-2']?'A':'B';match.status='completed';match.completed_at=now.toISOString();await client.query("UPDATE card_records SET data=$2::jsonb WHERE collection='debug_matches' AND record_key=$1",[key,JSON.stringify(match)]);return match;}
export const resetWutDebugMatchPostgres=(pool,userId,now)=>withTransaction(pool,client=>resetWutDebugMatchWithClient(client,userId,now));
export const commitWutDebugPlacementPostgres=(pool,input)=>withTransaction(pool,client=>commitWutDebugPlacementWithClient(client,input));
export const completeWutDebugMatchPostgres=(pool,input)=>withTransaction(pool,client=>completeWutDebugMatchWithClient(client,input));
