CREATE SEQUENCE IF NOT EXISTS users_id_seq;
CREATE SEQUENCE IF NOT EXISTS bets_id_seq;
CREATE SEQUENCE IF NOT EXISTS balance_transactions_id_seq;
CREATE SEQUENCE IF NOT EXISTS casino_spins_id_seq;
CREATE SEQUENCE IF NOT EXISTS shot_doctor_runs_id_seq;
CREATE SEQUENCE IF NOT EXISTS owned_cards_id_seq;
CREATE SEQUENCE IF NOT EXISTS owned_boosts_id_seq;
CREATE SEQUENCE IF NOT EXISTS owned_trinkets_id_seq;
CREATE SEQUENCE IF NOT EXISTS wut_decks_id_seq;
CREATE SEQUENCE IF NOT EXISTS pack_purchases_id_seq;
CREATE SEQUENCE IF NOT EXISTS wut_transactions_id_seq;
CREATE SEQUENCE IF NOT EXISTS arena_entries_id_seq;
CREATE SEQUENCE IF NOT EXISTS draft_presets_id_seq;
CREATE SEQUENCE IF NOT EXISTS draft_events_id_seq;

ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_id_seq');
ALTER TABLE bets ALTER COLUMN id SET DEFAULT nextval('bets_id_seq');
ALTER TABLE balance_transactions ALTER COLUMN id SET DEFAULT nextval('balance_transactions_id_seq');
ALTER TABLE casino_spins ALTER COLUMN id SET DEFAULT nextval('casino_spins_id_seq');
ALTER TABLE shot_doctor_runs ALTER COLUMN id SET DEFAULT nextval('shot_doctor_runs_id_seq');
ALTER TABLE owned_cards ALTER COLUMN id SET DEFAULT nextval('owned_cards_id_seq');
ALTER TABLE owned_boosts ALTER COLUMN id SET DEFAULT nextval('owned_boosts_id_seq');
ALTER TABLE owned_trinkets ALTER COLUMN id SET DEFAULT nextval('owned_trinkets_id_seq');
ALTER TABLE wut_decks ALTER COLUMN id SET DEFAULT nextval('wut_decks_id_seq');
ALTER TABLE pack_purchases ALTER COLUMN id SET DEFAULT nextval('pack_purchases_id_seq');
ALTER TABLE wut_transactions ALTER COLUMN id SET DEFAULT nextval('wut_transactions_id_seq');
ALTER TABLE arena_entries ALTER COLUMN id SET DEFAULT nextval('arena_entries_id_seq');
ALTER TABLE draft_presets ALTER COLUMN id SET DEFAULT nextval('draft_presets_id_seq');
ALTER TABLE draft_events ALTER COLUMN id SET DEFAULT nextval('draft_events_id_seq');

SELECT setval('users_id_seq', COALESCE((SELECT max(id) + 1 FROM users), 1), false);
SELECT setval('bets_id_seq', COALESCE((SELECT max(id) + 1 FROM bets), 1), false);
SELECT setval('balance_transactions_id_seq', COALESCE((SELECT max(id) + 1 FROM balance_transactions), 1), false);
SELECT setval('casino_spins_id_seq', COALESCE((SELECT max(id) + 1 FROM casino_spins), 1), false);
SELECT setval('shot_doctor_runs_id_seq', COALESCE((SELECT max(id) + 1 FROM shot_doctor_runs), 1), false);
SELECT setval('owned_cards_id_seq', COALESCE((SELECT max(id) + 1 FROM owned_cards), 1), false);
SELECT setval('owned_boosts_id_seq', COALESCE((SELECT max(id) + 1 FROM owned_boosts), 1), false);
SELECT setval('owned_trinkets_id_seq', COALESCE((SELECT max(id) + 1 FROM owned_trinkets), 1), false);
SELECT setval('wut_decks_id_seq', COALESCE((SELECT max(id) + 1 FROM wut_decks), 1), false);
SELECT setval('pack_purchases_id_seq', COALESCE((SELECT max(id) + 1 FROM pack_purchases), 1), false);
SELECT setval('wut_transactions_id_seq', COALESCE((SELECT max(id) + 1 FROM wut_transactions), 1), false);
SELECT setval('arena_entries_id_seq', COALESCE((SELECT max(id) + 1 FROM arena_entries), 1), false);
SELECT setval('draft_presets_id_seq', COALESCE((SELECT max(id) + 1 FROM draft_presets), 1), false);
SELECT setval('draft_events_id_seq', COALESCE((SELECT max(id) + 1 FROM draft_events), 1), false);
